channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - bcftools=1.3.1
  - bwa=0.7.12
  - pyyaml=3.11
  - htseq=0.9.1=py35_0
  - pysam=0.10.0=py35_1
  - bwa=0.7.12
  - circexplorer2=2.3.2
  - pybedtools=0.7.10
  - samtools=1.3.1
  - docopt=0.6.2
  - scipy=1.0.0
 # - python=2.7 - python=2.7

